# Autogenerated wrapper script for libjwt_jll for i686-w64-mingw32
export jwtauth, jwtgen, libjwt

using OpenSSL_jll
using Jansson_jll
JLLWrappers.@generate_wrapper_header("libjwt")
JLLWrappers.@declare_library_product(libjwt, "libjwt-2.dll")
JLLWrappers.@declare_executable_product(jwtauth)
JLLWrappers.@declare_executable_product(jwtgen)
function __init__()
    JLLWrappers.@generate_init_header(OpenSSL_jll, Jansson_jll)
    JLLWrappers.@init_library_product(
        libjwt,
        "bin\\libjwt-2.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        jwtauth,
        "bin\\jwtauth.exe",
    )

    JLLWrappers.@init_executable_product(
        jwtgen,
        "bin\\jwtgen.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
