# Autogenerated wrapper script for libjwt_jll for x86_64-linux-gnu
export jwtauth, jwtgen, libjwt

using OpenSSL_jll
using Jansson_jll
JLLWrappers.@generate_wrapper_header("libjwt")
JLLWrappers.@declare_library_product(libjwt, "libjwt.so.2")
JLLWrappers.@declare_executable_product(jwtauth)
JLLWrappers.@declare_executable_product(jwtgen)
function __init__()
    JLLWrappers.@generate_init_header(OpenSSL_jll, Jansson_jll)
    JLLWrappers.@init_library_product(
        libjwt,
        "lib/libjwt.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        jwtauth,
        "bin/jwtauth",
    )

    JLLWrappers.@init_executable_product(
        jwtgen,
        "bin/jwtgen",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
